sudo: required

language: python

services:
  - docker

install:
  - pip install ome-ansible-molecule-dependencies

script:
 - molecule test || echo "Failed"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
