---
sudo: required
language: python

services:
  - docker

install:
  - pip install ome-ansible-molecule-dependencies

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
